### ISSUE TITLE
Not an issue, rather a question

### ISSUE THREAD

**Issue by kapyaar** [gregington/SMTPClient#1]
Hi, I was wondering if there is a way to use this library  and get ssl support on an arduino due? I am looking to send mail from my Due board using gmail's smtp server.

**Comment by gregington** [comment]
In this code I'm using the general purpose TCP client library to talk to the mail server and this does not support SSL.

I suspect, given the limitations of the Arduno hardware, there will never be such a library and thus I won't be able to support sending mail via SSL.

**Comment by kapyaar** [comment]
Even ARduino Due with 32bit Arm core not good?

## 

Avarachan

**Comment by gregington** [comment]
It may be possible, but I have no plans to write or port an SSL library to the Due. If such a library were available, I would look at modifying SMTPClient to support it.

As it is, I don't think any such library exists, and is doubtful if the Due has enough memory to run SSL (even though the processor may be adequate). See http://arduino.stackexchange.com/questions/4/how-to-get-https-on-arduino, and https://github.com/sirleech/Webduino/issues/29 and http://stackoverflow.com/questions/15830333/arduino-due-https-support.

You may want to consider using a Raspberry Pi, or Arduino Yun instead of the Due if it's possible for your application.

**Comment by kapyaar** [comment]
Hi,

I was reading further over the past week into different ssl libraries. I
came across the following.

1.
https://github.com/ARMmbed/mbedtls/blob/master/programs/ssl/ssl_mail_client.c
2. https://www.wolfssl.com/wolfSSL/Products-wolfssl.html

To have a  mail client alone, Are any of these worth looking at? I am aware
of Pi, Yun and few other board options, but I have some custom board design
ideas so I am not quitting arduino yet.

best regards,

## 

Avarachan
